modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-3"
issueTrackerURL="https://github.com/PandaDap2006/PandaLib/issues"
showAsResourcePack=false

[[mods]]
modId = "pandalib"
version = "${version}"
displayName = "PandaLib"
authors = "The Panda Oliver"
logoFile = "icon.png"
description = "A multi purpose library with a Config API and a bit of utility code. More features planned"

[[dependencies.pandalib]]
modId = "neoforge"
type = "required"
versionRange = "[20.5.21-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "architectury"
type = "required"
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "pandalib-common.mixins.json"
[[mixins]]
config = "pandalib.mixins.json"